project_id = "foifugnuaehjtjftpkrk"

[functions.traccar-proxy]
verify_jwt = false

[functions.create-tenant]
verify_jwt = false

[functions.traccar-events-poller]
verify_jwt = false

[functions.onesignal-notify]
verify_jwt = false
